events {
    worker_connections 1024;
}

http {
    # Указываем имя сервиса из docker-compose и порт NestJS (по умолчанию 3000)
    upstream nestjs_backend {
        server app:3000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://nestjs_backend;
            proxy_http_version 1.1;

            # Заголовки для корректной работы с NestJS (CORS, WebSockets, реальный IP)
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }
    }
}